import { TGenerateStylesProps } from './type';
declare const generateStyles: (props?: TGenerateStylesProps) => {
    container: string;
    controllerContent: string;
    controllerContentEnable: string;
    headController: string;
    headControllerTitle: string;
    bodyController: string;
    buttonPlayPrimary: string;
    settingsContainer: string;
    settingsContent: string;
    settingHeader: string;
    settingItem: string;
    settingDetailItem: string;
    settingItemDivider: string;
    settingTitleActive: string;
    settingTitleNormal: string;
    settingItemIcon: string;
    settingItemIconSecondary: string;
    settingItemTitle: string;
    settingItemValue: string;
    buttonPlayPrimaryEnable: string;
    footerController: string;
    seekBarController: string;
    taskbarController: string;
    taskbarGroup: string;
    taskbarGroupBtn: string;
    taskbarGroupBtnEnable: string;
    loadingContainer: string;
    loadingContainerEnable: string;
    errorContainer: string;
    errorContainerEnable: string;
    errorIconWrap: string;
    flexColumnStartCenter: string;
};
export default generateStyles;
//# sourceMappingURL=style.d.ts.map