export const ids = {
  smControllerContainer: 'sm-controller-container',
  smControllerContent: 'sm-controller-content',
  smLoading: 'sm-loading',
  smError: 'sm-error',
  smHeadController: 'sm-head-controller',
  smBodyController: 'sm-body-controller',
  smButtonPlayPrimary: 'sm-button-play-primary',
  smSettingsContainer: 'sm-settings-container',
  smSettingsContainerMask: 'sm-settings-container-mask',
  smSettingDetailTitle: 'sm-settings-detail-title',
  smSettingDetailGoBackIcon: 'sm-settings-detail-go-back-icon',
  smSettingPlaybackSpeedItemPrefix: 'sm-settings-playback-speed-item',
  smSettingQualityItemPrefix: 'sm-settings-quality-item',
  smFooterController: 'sm-footer-controller',
  smTaskbarController: 'sm-taskbar-controller',
  smSeekBarController: 'sm-seek-bar-controller',
  smButtonFullScreen: 'sm-button-full-screen',
  smButtonPlaySecondary: 'sm-button-play-secondary',
  smButtonPauseSecondary: 'sm-button-pause-secondary',
  smButtonForward: 'sm-button-forward',
  smButtonReply: 'sm-button-reply',
  smButtonExitFullScreen: 'sm-button-exit-full-screen',
  smButtonVolume: 'sm-button-volume',
  smButtonMute: 'sm-button-mute',
  smSelectVolumeRange: 'sm-select-volume-range',
  smInputVolumeRange: 'sm-input-volume-range',
  smVolumeContainer: 'sm-volume-container',
  smPlaybackSpeed: 'sm-playback-rate-controller',
  smQuality: 'sm-quality-controller',
  smSettingIconButton: 'sm-setting-icon-button',
  smTimeBarContainer: 'sm-time-bar-container',
  smTaskbarLiveStream: 'sm-taskbar-live-stream',
  smTimeCurrent: 'sm-time-current',
  smTimeDuration: 'sm-time-duration',
  smProgressBar: 'sm-progress-bar',
  smProgressThumb: 'sm-progress-thumb',
  smProgressBarContainer: 'sm-progress-bar-container',
  smProgressBuffer: 'sm-progress-buffer',
};
export const versionDef = '4.10.0';

export enum ETypePlayer {
  SHAKA = 'SHAKA',
  VIDEOSJS = 'VIDEOSJS',
}
export const typePlayerDef = ETypePlayer.SHAKA;
export const primaryColorDef = '#F58220';
